from pydantic import BaseModel, Field
from typing import List, Optional

class TraceabilityRef(BaseModel):
    """
    Reference to a retrieved code chunk context for auditability.
    """
    path: str = Field(..., description="Relative path of the source file")
    start_line: int = Field(..., description="Start line of the chunk")
    end_line: int = Field(..., description="End line of the chunk")
    chunk_id: str = Field(..., description="Unique chunk identifier")
    score: Optional[float] = Field(None, description="Similarity score of the chunk")

class AIMetadata(BaseModel):
    """
    Runtime metrics, model identifiers, and latency statistics for AI operations.
    """
    provider: str = Field(..., description="The configured LLM provider name")
    provider_used_after_failover: Optional[str] = Field(None, description="The final provider name if failover occurred")
    model: str = Field(..., description="The model name used for processing")
    latency: float = Field(..., description="Latency of the LLM call in seconds")
    prompt_tokens: int = Field(0, description="Tokens in the prompt sent to the LLM")
    completion_tokens: int = Field(0, description="Tokens generated by the LLM")
    total_tokens: int = Field(0, description="Total tokens consumed")
    retry_count: int = Field(0, description="Number of retries attempted before success")
    cache_hit: bool = Field(False, description="True if response was loaded from cache")
    fallback_flag: bool = Field(False, description="True if system failed back to static heuristic execution")
    request_id: str = Field(..., description="Unique transaction request UUID")
    started_timestamp: float = Field(..., description="Unix timestamp of when AI task execution started")
    completed_timestamp: float = Field(..., description="Unix timestamp of when AI task execution completed")
    estimated_cost: float = Field(0.0, description="Estimated USD cost of provider query")

class BaseAISchema(BaseModel):
    """
    Unified base AI response schema containing diagnostic fields and reference mappings.
    """
    is_fallback: bool = Field(False, description="True if the response utilizes local heuristic fallback metrics")
    traceability_refs: List[TraceabilityRef] = Field(default_factory=list, description="Collection of traceability references used to build report findings")
    ai_metadata: Optional[AIMetadata] = Field(None, description="AI execution tracking metadata")
