"""
Chat ORM Models — Phase 5

Defines two new tables:
  - chat_conversations  : One session per (repository, user intent)
  - chat_messages       : Individual turns (user or assistant) within a session

Both tables are linked to the existing `repositories` table via FK.
Cascade DELETE ensures removing a repository cleans up all its conversations.
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column,
    String,
    Integer,
    Float,
    Boolean,
    DateTime,
    Text,
    ForeignKey,
    Index,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from app.db.database import Base


def _new_uuid() -> str:
    return str(uuid.uuid4())


class ChatConversation(Base):
    """
    Represents one chat session scoped to a single indexed repository.

    title         : Auto-generated from the first user message (first 80 chars).
    message_count : Denormalized counter; updated on each new ChatMessage to
                    avoid COUNT(*) on every list query.
    updated_at    : Refreshed on every new message for recency sorting.
    """

    __tablename__ = "chat_conversations"

    id = Column(String, primary_key=True, default=_new_uuid)
    repository_id = Column(
        String,
        ForeignKey("repositories.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title = Column(String(500), nullable=True)
    message_count = Column(Integer, nullable=False, default=0)
    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None))
    updated_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None), onupdate=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    # Relationships
    messages = relationship(
        "ChatMessage",
        back_populates="conversation",
        cascade="all, delete-orphan",
        order_by="ChatMessage.created_at",
    )
    repository = relationship("Repository", back_populates="chat_conversations")

    __table_args__ = (
        Index("idx_chat_conv_repo_updated", "repository_id", "updated_at"),
    )


class ChatMessage(Base):
    """
    Represents one conversational turn — either a user question or an
    AI-generated answer.

    role                : "user" | "assistant" | "system"
    content             : Full markdown body of the message.
    citations           : JSONB list of {path, start_line, end_line, score}
                          extracted from the LLM structured response.
    follow_up_questions : JSONB list of suggested next questions (max 3).
    provider / model    : Which LLM serviced this message (assistant only).
    latency             : Seconds from request start to first token.
    prompt_tokens       : Tokens in the assembled prompt.
    completion_tokens   : Tokens generated by the LLM.
    is_fallback         : True when all providers failed and a static fallback
                          response was returned.
    """

    __tablename__ = "chat_messages"

    id = Column(String, primary_key=True, default=_new_uuid)
    conversation_id = Column(
        String,
        ForeignKey("chat_conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    role = Column(String(16), nullable=False)  # "user" | "assistant" | "system"
    content = Column(Text, nullable=False)
    citations = Column(JSONB, nullable=True)            # [{path, start_line, end_line, score}]
    follow_up_questions = Column(JSONB, nullable=True)  # [str, str, str]

    # Provider telemetry (populated for assistant messages only)
    provider = Column(String(64), nullable=True)
    model = Column(String(128), nullable=True)
    latency = Column(Float, nullable=True)
    prompt_tokens = Column(Integer, nullable=True)
    completion_tokens = Column(Integer, nullable=True)
    is_fallback = Column(Boolean, nullable=False, default=False)

    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    # Relationships
    conversation = relationship("ChatConversation", back_populates="messages")

    __table_args__ = (
        Index("idx_chat_msg_conv_created", "conversation_id", "created_at"),
    )


# ---------------------------------------------------------------------------
# Avoid circular import: import Repository at module bottom so SQLAlchemy
# relationship resolution works correctly (same pattern as other models).
# ---------------------------------------------------------------------------
from app.models.repository import Repository  # noqa: E402, F401
