"""Planning Engine rule definitions.

Defines the structure, agents, dependencies, and settings for each goal intent.
"""

from typing import Any, Dict, List

PLANNING_RULES: Dict[str, Dict[str, Any]] = {
    "Security Audit": {
        "intent": "Security Audit",
        "workflow_category": "security",
        "priority": 8,
        "risk": "medium",
        "complexity": "medium",
        "allows_parallel_execution": True,
        "requires_repository_analysis": True,
        "requires_graph_context": True,
        "estimated_tokens": 12000,
        "parallel_groups": ["repository", "analysis", "summary"],
        "steps": [
            {
                "step_id": "step_repo",
                "agent": "Repository Agent",
                "title": "Ingest Workspace Details",
                "description": "Analyze repository file tree, database schemas, and external configuration properties.",
                "execution_group": "repository",
                "estimated_duration": 15,
                "estimated_token_cost": 2000,
            },
            {
                "step_id": "step_security",
                "agent": "Security Agent",
                "title": "Perform Security Audit Scan",
                "description": "Search code files for secret leaks, cryptographical misuse, and OWASP Top 10 vulnerabilities.",
                "execution_group": "analysis",
                "estimated_duration": 25,
                "estimated_token_cost": 4000,
            },
            {
                "step_id": "step_deps",
                "agent": "Dependency Analysis",
                "title": "Inspect Dependencies Vulnerability",
                "description": "Check configuration package lists for outdated packages and vulnerable components.",
                "execution_group": "analysis",
                "estimated_duration": 20,
                "estimated_token_cost": 3000,
            },
            {
                "step_id": "step_summary",
                "agent": "Summary Agent",
                "title": "Synthesize Security Report",
                "description": "Consolidate the findings from audit and dependency scans into a structured report.",
                "execution_group": "summary",
                "estimated_duration": 15,
                "estimated_token_cost": 3000,
            },
        ],
        "dependencies": [
            {"source_step_id": "step_repo", "target_step_id": "step_security"},
            {"source_step_id": "step_repo", "target_step_id": "step_deps"},
            {"source_step_id": "step_security", "target_step_id": "step_summary"},
            {"source_step_id": "step_deps", "target_step_id": "step_summary"},
        ],
        "optional_agents": ["Testing Agent"],
    },
    "Documentation": {
        "intent": "Documentation",
        "workflow_category": "docs",
        "priority": 3,
        "risk": "low",
        "complexity": "low",
        "allows_parallel_execution": True,
        "requires_repository_analysis": False,
        "requires_graph_context": True,
        "estimated_tokens": 8000,
        "parallel_groups": ["repository", "analysis", "summary"],
        "steps": [
            {
                "step_id": "step_repo",
                "agent": "Repository Agent",
                "title": "Scan Module Hierarchies",
                "description": "Map module files, structural packages, and entrypoints to document.",
                "execution_group": "repository",
                "estimated_duration": 10,
                "estimated_token_cost": 1500,
            },
            {
                "step_id": "step_docs",
                "agent": "Documentation Agent",
                "title": "Generate Codebase Documentation",
                "description": "Draft clean Markdown documentation detailing components, functions, and architecture layout.",
                "execution_group": "analysis",
                "estimated_duration": 30,
                "estimated_token_cost": 4500,
            },
            {
                "step_id": "step_summary",
                "agent": "Summary Agent",
                "title": "Compile Documentation Guide",
                "description": "Consolidate structural layout pages and generate index menus.",
                "execution_group": "summary",
                "estimated_duration": 10,
                "estimated_token_cost": 2000,
            },
        ],
        "dependencies": [
            {"source_step_id": "step_repo", "target_step_id": "step_docs"},
            {"source_step_id": "step_docs", "target_step_id": "step_summary"},
        ],
        "optional_agents": [],
    },
    "Refactoring": {
        "intent": "Refactoring",
        "workflow_category": "refactor",
        "priority": 7,
        "risk": "high",
        "complexity": "high",
        "allows_parallel_execution": True,
        "requires_repository_analysis": True,
        "requires_graph_context": True,
        "estimated_tokens": 15000,
        "parallel_groups": ["repository", "analysis", "refactoring", "summary"],
        "steps": [
            {
                "step_id": "step_repo",
                "agent": "Repository Agent",
                "title": "Trace Component Coupling",
                "description": "Analyze coupling degrees and dependency links for files targeted for refactoring.",
                "execution_group": "repository",
                "estimated_duration": 15,
                "estimated_token_cost": 2500,
            },
            {
                "step_id": "step_review",
                "agent": "Review Agent",
                "title": "Formulate Refactoring Strategy",
                "description": "Perform static checks on coupling structures and locate duplication smells.",
                "execution_group": "analysis",
                "estimated_duration": 25,
                "estimated_token_cost": 4000,
            },
            {
                "step_id": "step_refactor",
                "agent": "Refactor Agent",
                "title": "Apply Refactor Workspace Edits",
                "description": "Introduce functional code changes to separate concerns and reduce coupling.",
                "execution_group": "refactoring",
                "estimated_duration": 35,
                "estimated_token_cost": 5500,
            },
            {
                "step_id": "step_summary",
                "agent": "Summary Agent",
                "title": "Summarize Workspace Modifications",
                "description": "Detail changes introduced, files affected, and verification recommendations.",
                "execution_group": "summary",
                "estimated_duration": 15,
                "estimated_token_cost": 3000,
            },
        ],
        "dependencies": [
            {"source_step_id": "step_repo", "target_step_id": "step_review"},
            {"source_step_id": "step_review", "target_step_id": "step_refactor"},
            {"source_step_id": "step_refactor", "target_step_id": "step_summary"},
        ],
        "optional_agents": ["Testing Agent"],
    },
    "Performance": {
        "intent": "Performance",
        "workflow_category": "optimize",
        "priority": 6,
        "risk": "medium",
        "complexity": "medium",
        "allows_parallel_execution": True,
        "requires_repository_analysis": True,
        "requires_graph_context": True,
        "estimated_tokens": 11000,
        "parallel_groups": ["repository", "analysis", "summary"],
        "steps": [
            {
                "step_id": "step_repo",
                "agent": "Repository Agent",
                "title": "Scan Database & Call Spans",
                "description": "Identify bottlenecks, queries, and call loops in index controllers.",
                "execution_group": "repository",
                "estimated_duration": 12,
                "estimated_token_cost": 2000,
            },
            {
                "step_id": "step_perf",
                "agent": "Performance Agent",
                "title": "Analyze Execution Latency Hotspots",
                "description": "Diagnose memory leaks, thread locks, and sub-optimal loops in core services.",
                "execution_group": "analysis",
                "estimated_duration": 25,
                "estimated_token_cost": 6000,
            },
            {
                "step_id": "step_summary",
                "agent": "Summary Agent",
                "title": "Synthesize Performance Insights",
                "description": "Generate performance improvement guidelines and latency estimations.",
                "execution_group": "summary",
                "estimated_duration": 12,
                "estimated_token_cost": 3000,
            },
        ],
        "dependencies": [
            {"source_step_id": "step_repo", "target_step_id": "step_perf"},
            {"source_step_id": "step_perf", "target_step_id": "step_summary"},
        ],
        "optional_agents": ["Refactor Agent"],
    },
    "Testing": {
        "intent": "Testing",
        "workflow_category": "testing",
        "priority": 5,
        "risk": "medium",
        "complexity": "medium",
        "allows_parallel_execution": True,
        "requires_repository_analysis": False,
        "requires_graph_context": True,
        "estimated_tokens": 10000,
        "parallel_groups": ["repository", "analysis", "summary"],
        "steps": [
            {
                "step_id": "step_repo",
                "agent": "Repository Agent",
                "title": "Inspect Test coverage structures",
                "description": "Scan tests folder layout and list target implementation classes.",
                "execution_group": "repository",
                "estimated_duration": 10,
                "estimated_token_cost": 1500,
            },
            {
                "step_id": "step_test",
                "agent": "Testing Agent",
                "title": "Draft Unit and Integration Suites",
                "description": "Write pytest or vitest test cases targeting untested code paths.",
                "execution_group": "analysis",
                "estimated_duration": 30,
                "estimated_token_cost": 5500,
            },
            {
                "step_id": "step_summary",
                "agent": "Summary Agent",
                "title": "Compile Testing Status Report",
                "description": "Log test coverage outcomes and verification instructions.",
                "execution_group": "summary",
                "estimated_duration": 10,
                "estimated_token_cost": 3000,
            },
        ],
        "dependencies": [
            {"source_step_id": "step_repo", "target_step_id": "step_test"},
            {"source_step_id": "step_test", "target_step_id": "step_summary"},
        ],
        "optional_agents": [],
    },
    "Bug Fix": {
        "intent": "Bug Fix",
        "workflow_category": "fix",
        "priority": 9,
        "risk": "high",
        "complexity": "medium",
        "allows_parallel_execution": True,
        "requires_repository_analysis": True,
        "requires_graph_context": True,
        "estimated_tokens": 14000,
        "parallel_groups": ["repository", "analysis", "refactoring", "summary"],
        "steps": [
            {
                "step_id": "step_repo",
                "agent": "Repository Agent",
                "title": "Locate Exception Stacktraces",
                "description": "Search codebase for faulty functions matching bug logs.",
                "execution_group": "repository",
                "estimated_duration": 15,
                "estimated_token_cost": 2500,
            },
            {
                "step_id": "step_review",
                "agent": "Review Agent",
                "title": "Perform Root Cause Analysis",
                "description": "Inspect logic parameters, loops, and conditions to isolate the defect.",
                "execution_group": "analysis",
                "estimated_duration": 25,
                "estimated_token_cost": 4500,
            },
            {
                "step_id": "step_refactor",
                "agent": "Refactor Agent",
                "title": "Apply Hotfix Workspace Changes",
                "description": "Introduce fix changes to restore correct execution behaviors.",
                "execution_group": "refactoring",
                "estimated_duration": 25,
                "estimated_token_cost": 4000,
            },
            {
                "step_id": "step_summary",
                "agent": "Summary Agent",
                "title": "Compile Fix Documentation Report",
                "description": "Detail root cause variables, introduced changes, and verification checks.",
                "execution_group": "summary",
                "estimated_duration": 12,
                "estimated_token_cost": 3000,
            },
        ],
        "dependencies": [
            {"source_step_id": "step_repo", "target_step_id": "step_review"},
            {"source_step_id": "step_review", "target_step_id": "step_refactor"},
            {"source_step_id": "step_refactor", "target_step_id": "step_summary"},
        ],
        "optional_agents": ["Testing Agent"],
    },
    "Architecture Review": {
        "intent": "Architecture Review",
        "workflow_category": "audit",
        "priority": 4,
        "risk": "low",
        "complexity": "low",
        "allows_parallel_execution": True,
        "requires_repository_analysis": True,
        "requires_graph_context": True,
        "estimated_tokens": 10000,
        "parallel_groups": ["repository", "analysis", "summary"],
        "steps": [
            {
                "step_id": "step_repo",
                "agent": "Repository Agent",
                "title": "Map Structural Subsystems",
                "description": "Inspect system layers, configurations, and core module linkages.",
                "execution_group": "repository",
                "estimated_duration": 12,
                "estimated_token_cost": 2000,
            },
            {
                "step_id": "step_review",
                "agent": "Review Agent",
                "title": "Evaluate Design Patterns",
                "description": "Verify layered patterns compliance and identify module abstraction leaks.",
                "execution_group": "analysis",
                "estimated_duration": 20,
                "estimated_token_cost": 5000,
            },
            {
                "step_id": "step_summary",
                "agent": "Summary Agent",
                "title": "Assemble Design Recommendations",
                "description": "Generate structural refactoring pathways and architecture grade sheets.",
                "execution_group": "summary",
                "estimated_duration": 10,
                "estimated_token_cost": 3000,
            },
        ],
        "dependencies": [
            {"source_step_id": "step_repo", "target_step_id": "step_review"},
            {"source_step_id": "step_review", "target_step_id": "step_summary"},
        ],
        "optional_agents": [],
    },
    "Dependency Analysis": {
        "intent": "Dependency Analysis",
        "workflow_category": "audit",
        "priority": 4,
        "risk": "low",
        "complexity": "low",
        "allows_parallel_execution": True,
        "requires_repository_analysis": True,
        "requires_graph_context": True,
        "estimated_tokens": 9000,
        "parallel_groups": ["repository", "analysis", "summary"],
        "steps": [
            {
                "step_id": "step_repo",
                "agent": "Repository Agent",
                "title": "Resolve Imports Tree",
                "description": "Scan internal package dependencies and list external dependencies components.",
                "execution_group": "repository",
                "estimated_duration": 10,
                "estimated_token_cost": 1500,
            },
            {
                "step_id": "step_deps",
                "agent": "Dependency Analysis",
                "title": "Audit Dependency Links",
                "description": "Evaluate dependency graph properties, tracking cycles and redundant modules.",
                "execution_group": "analysis",
                "estimated_duration": 20,
                "estimated_token_cost": 4500,
            },
            {
                "step_id": "step_summary",
                "agent": "Summary Agent",
                "title": "Synthesize Dependency Analysis Report",
                "description": "Report on package vulnerabilities, cycles, and cleanup recommendations.",
                "execution_group": "summary",
                "estimated_duration": 10,
                "estimated_token_cost": 3000,
            },
        ],
        "dependencies": [
            {"source_step_id": "step_repo", "target_step_id": "step_deps"},
            {"source_step_id": "step_deps", "target_step_id": "step_summary"},
        ],
        "optional_agents": [],
    },
    "Feature Implementation": {
        "intent": "Feature Implementation",
        "workflow_category": "feature",
        "priority": 8,
        "risk": "high",
        "complexity": "high",
        "allows_parallel_execution": True,
        "requires_repository_analysis": True,
        "requires_graph_context": True,
        "estimated_tokens": 18000,
        "parallel_groups": ["repository", "analysis", "refactoring", "summary"],
        "steps": [
            {
                "step_id": "step_repo",
                "agent": "Repository Agent",
                "title": "Locate Target Classes",
                "description": "Locate entry endpoints and controller routes to integrate the new feature.",
                "execution_group": "repository",
                "estimated_duration": 15,
                "estimated_token_cost": 2500,
            },
            {
                "step_id": "step_review",
                "agent": "Review Agent",
                "title": "Outline Integration Points",
                "description": "Design function signatures, modules, and API payload expectations.",
                "execution_group": "analysis",
                "estimated_duration": 25,
                "estimated_token_cost": 4500,
            },
            {
                "step_id": "step_refactor",
                "agent": "Refactor Agent",
                "title": "Implement Feature Source Edits",
                "description": "Write and apply new components, functions, or router configurations.",
                "execution_group": "refactoring",
                "estimated_duration": 35,
                "estimated_token_cost": 6000,
            },
            {
                "step_id": "step_test",
                "agent": "Testing Agent",
                "title": "Verify Feature Integrity",
                "description": "Add new verification cases targeting the newly implemented classes.",
                "execution_group": "analysis",
                "estimated_duration": 25,
                "estimated_token_cost": 4000,
            },
            {
                "step_id": "step_summary",
                "agent": "Summary Agent",
                "title": "Compile Implementation Review",
                "description": "Detail features introduced, tests run, and deployment notes.",
                "execution_group": "summary",
                "estimated_duration": 15,
                "estimated_token_cost": 3000,
            },
        ],
        "dependencies": [
            {"source_step_id": "step_repo", "target_step_id": "step_review"},
            {"source_step_id": "step_review", "target_step_id": "step_refactor"},
            {"source_step_id": "step_refactor", "target_step_id": "step_test"},
            {"source_step_id": "step_test", "target_step_id": "step_summary"},
        ],
        "optional_agents": [],
    },
    "General Analysis": {
        "intent": "General Analysis",
        "workflow_category": "audit",
        "priority": 5,
        "risk": "low",
        "complexity": "low",
        "allows_parallel_execution": True,
        "requires_repository_analysis": False,
        "requires_graph_context": True,
        "estimated_tokens": 9000,
        "parallel_groups": ["repository", "analysis", "summary"],
        "steps": [
            {
                "step_id": "step_repo",
                "agent": "Repository Agent",
                "title": "Collect Base Metadata",
                "description": "Resolve modules layout, folders, and key entrypoint links.",
                "execution_group": "repository",
                "estimated_duration": 10,
                "estimated_token_cost": 1500,
            },
            {
                "step_id": "step_review",
                "agent": "Review Agent",
                "title": "Analyze Goal Contexts",
                "description": "Run basic semantic queries and graph hops for goal specifications.",
                "execution_group": "analysis",
                "estimated_duration": 20,
                "estimated_token_cost": 4500,
            },
            {
                "step_id": "step_summary",
                "agent": "Summary Agent",
                "title": "Formulate Goal Response",
                "description": "Synthesize the analysis findings and recommendations.",
                "execution_group": "summary",
                "estimated_duration": 10,
                "estimated_token_cost": 3000,
            },
        ],
        "dependencies": [
            {"source_step_id": "step_repo", "target_step_id": "step_review"},
            {"source_step_id": "step_review", "target_step_id": "step_summary"},
        ],
        "optional_agents": [],
    },
}
