"""add_repository_stats

Revision ID: 84d182212858
Revises: d74a64e30e1f
Create Date: 2026-07-08 12:12:14.282195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d182212858'
down_revision: Union[str, Sequence[str], None] = 'd74a64e30e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('total_files', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('directories', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('extensions', sa.JSON(), nullable=True))
    op.add_column('repositories', sa.Column('largest_files', sa.JSON(), nullable=True))
    op.add_column('repositories', sa.Column('dependencies', sa.JSON(), nullable=True))
    op.add_column('repositories', sa.Column('package_managers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'package_managers')
    op.drop_column('repositories', 'dependencies')
    op.drop_column('repositories', 'largest_files')
    op.drop_column('repositories', 'extensions')
    op.drop_column('repositories', 'directories')
    op.drop_column('repositories', 'total_files')
    # ### end Alembic commands ###
