"""add_repository_more_stats

Revision ID: c91b4d203704
Revises: 84d182212858
Create Date: 2026-07-08 12:20:39.113232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91b4d203704'
down_revision: Union[str, Sequence[str], None] = '84d182212858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('default_branch', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('readme_present', sa.Boolean(), nullable=True))
    op.add_column('repositories', sa.Column('license', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('docker_support', sa.Boolean(), nullable=True))
    op.add_column('repositories', sa.Column('github_actions', sa.Boolean(), nullable=True))
    op.add_column('repositories', sa.Column('cicd', sa.Boolean(), nullable=True))
    op.add_column('repositories', sa.Column('tests_present', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'tests_present')
    op.drop_column('repositories', 'cicd')
    op.drop_column('repositories', 'github_actions')
    op.drop_column('repositories', 'docker_support')
    op.drop_column('repositories', 'license')
    op.drop_column('repositories', 'readme_present')
    op.drop_column('repositories', 'default_branch')
    # ### end Alembic commands ###
