from typing import List, Dict, Any

class ExecutionReport:
    """
    Builds the final structured execution report summarizing the autonomous workflow run.
    """
    def __init__(self, goal: str, execution_plan: List[Dict[str, Any]], context_dict: Dict[str, Any]):
        self.goal = goal
        self.execution_plan = execution_plan
        self.context = context_dict
        
        self.completed_steps = [s for s in context_dict.get("completed_steps", []) if s.get("status") == "completed"]
        self.failed_steps = [s for s in context_dict.get("completed_steps", []) if s.get("status") == "failed"]
        
        self.files_used = list(set([c.get("path") for c in context_dict.get("retrieved_chunks", [])]))
        self.chunks_used = context_dict.get("retrieved_chunks", [])
        
        self.agents_used = list(set([s.get("agent") for s in context_dict.get("completed_steps", []) if s.get("agent")]))
        self.tools_used = list(set([t.get("tool") for t in context_dict.get("tool_outputs", []) if t.get("tool")]))
        
        self.execution_time = context_dict.get("duration", 0.0)
        self.confidence = context_dict.get("confidence", 1.0)
        self.recommendations = self._extract_recommendations()
        
    def _extract_recommendations(self) -> List[str]:
        """
        Gathers recommendations generated by the individual specialized agents.
        """
        recs = []
        for out in self.context.get("agent_outputs", []):
            result = out.get("result", {})
            if isinstance(result, dict):
                # Search for lists of recommendations
                for key in ["recommendations", "improvements", "suggestions", "findings"]:
                    if key in result and isinstance(result[key], list):
                        for item in result[key]:
                            if isinstance(item, str):
                                recs.append(f"[{out.get('agent', 'Agent')}] {item}")
                            elif isinstance(item, dict) and "description" in item:
                                recs.append(f"[{out.get('agent', 'Agent')}] {item.get('description')}")
        if not recs:
            recs = ["No specific recommendations generated. Repository is in a healthy state."]
        return list(set(recs))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "goal": self.goal,
            "execution_plan": self.execution_plan,
            "completed_steps": self.completed_steps,
            "failed_steps": self.failed_steps,
            "files_used": self.files_used,
            "chunks_used": self.chunks_used,
            "agents_used": self.agents_used,
            "tools_used": self.tools_used,
            "execution_time": self.execution_time,
            "confidence": self.confidence,
            "recommendations": self.recommendations,
            "traceability": [
                {
                    "path": c.get("path"),
                    "start_line": c.get("start_line"),
                    "end_line": c.get("end_line"),
                    "score": c.get("score")
                } for c in self.chunks_used
            ]
        }
